# Generated by Django 3.0.7 on 2020-06-17 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MaServiceProvider', '0002_delete_ads'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaDere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('Namba_Zao', models.IntegerField()),
                ('price_per_km', models.FloatField()),
                ('location', models.CharField(max_length=255)),
                ('availability', models.BooleanField()),
                ('image_url', models.CharField(max_length=2083)),
                ('description', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('image_Ndai', models.ImageField(upload_to='Ma_Ndai')),
                ('license_verified', models.BooleanField(default=False)),
                ('AINA_YA_NDAI', models.CharField(choices=[('BI', 'Bike'), ('MK', 'MotorBike'), ('CR', 'Car'), ('LO', 'Lorry')], max_length=2)),
                ('WATEJA', models.CharField(choices=[('A', 'Passengers'), ('M', 'Mizigo')], max_length=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Addicts',
        ),
    ]
