# Generated by Django 3.1.1 on 2021-04-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20210423_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lnmonline',
            name='Amount',
            field=models.FloatField(editable=False),
        ),
        migrations.AlterField(
            model_name='lnmonline',
            name='Balance',
            field=models.CharField(blank=True, editable=False, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='lnmonline',
            name='CheckoutRequestID',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='lnmonline',
            name='MerchantRequestID',
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='lnmonline',
            name='MpesaReceiptNumber',
            field=models.CharField(editable=False, max_length=15),
        ),
        migrations.AlterField(
            model_name='lnmonline',
            name='PhoneNumber',
            field=models.CharField(editable=False, max_length=13),
        ),
        migrations.AlterField(
            model_name='lnmonline',
            name='ResultCode',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='lnmonline',
            name='ResultDesc',
            field=models.CharField(editable=False, max_length=120),
        ),
        migrations.AlterField(
            model_name='lnmonline',
            name='TransactionDate',
            field=models.DateTimeField(editable=False),
        ),
    ]
