# Generated by Django 3.1.1 on 2021-06-30 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('me2ushop', '0112_auto_20210630_1016'),
        ('payments', '0003_auto_20210423_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='DRCTransactionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, null=True, verbose_name='creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='modification date and time')),
                ('reference', models.CharField(max_length=200)),
                ('flutterwave_reference', models.CharField(max_length=200)),
                ('order_reference', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('charged_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('status', models.CharField(max_length=50)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='me2ushop.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drc_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Flutterwave Transaction',
                'verbose_name_plural': 'Flutterwave Transactions',
            },
        ),
    ]
