# Generated by Django 3.1.1 on 2021-06-30 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0004_drctransactionmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drctransactionmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drc_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
