# Generated by Django 3.0.7 on 2020-08-30 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller_profile',
            name='image',
        ),
        migrations.AddField(
            model_name='seller_profile',
            name='business_title',
            field=models.CharField(default='makori', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller_profile',
            name='business_type',
            field=models.CharField(choices=[('Co', 'Company'), ('Sol', 'Sole Proprietorship')], default='Sol', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller_profile',
            name='first_name',
            field=models.CharField(default='daniel', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller_profile',
            name='last_name',
            field=models.CharField(default='makori', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller_profile',
            name='subscription_type',
            field=models.CharField(choices=[('Bs', 'Basic'), ('Pr', 'Premium')], default='Bs', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller_profile',
            name='tax_country',
            field=django_countries.fields.CountryField(default='KE', max_length=2),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Automobile_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('passport_no', models.CharField(max_length=20)),
                ('automobile_type', models.CharField(choices=[('Cr', 'Car'), ('Pk', 'Pick Up'), ('Va', 'Van'), ('Bs', 'Bus'), ('Tr', 'Truck'), ('Mt', 'Motor'), ('Bc', 'Bicycle')], max_length=4)),
                ('date_of_registration', models.DateTimeField(auto_now_add=True)),
                ('country', models.CharField(choices=[('KE', 'Kenya'), ('UG', 'Uganda'), ('TZ', 'Tanzania'), ('RW', 'Rwanda')], max_length=2)),
                ('city_of_operation', models.CharField(choices=[('Kg', 'Kigali'), ('Kp', 'Kampala'), ('Nb', 'Nairobi'), ('Dd', 'Dodoma')], max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
