# Generated by Django 3.1.1 on 2020-10-29 08:19

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='images/products'),
        ),
    ]
