# Generated by Django 3.1.1 on 2021-01-22 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, verbose_name='creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='modification date and time')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('phone', models.CharField(blank=True, help_text='This number will be visible to buyers who would like to contact you for services', max_length=20, null=True)),
                ('website_link', models.CharField(blank=True, help_text='If you have a website by which buyers can find out more about your services', max_length=30, null=True)),
                ('facebook_page', models.CharField(blank=True, help_text='Do you have a facebook page. Copy paste your page link here', max_length=255, null=True)),
                ('instagram', models.CharField(blank=True, help_text='Do you have a instagram page. Copy paste your page link here', max_length=255, null=True)),
                ('telegram', models.CharField(blank=True, help_text='Do you have a Telegram Channel. Copy paste your page link here', max_length=100, null=True)),
                ('business_type', models.CharField(choices=[('Co', 'Company'), ('Sol', 'Sole Proprietorship')], max_length=4)),
                ('tax_country', django_countries.fields.CountryField(max_length=2)),
                ('subscription_type', models.CharField(choices=[('Bs', 'Basic'), ('Pr', 'Premium')], help_text='Select a monthly recurring subscription fees', max_length=2)),
                ('application_status', models.IntegerField(choices=[(10, 'Under Review'), (20, 'Accepted'), (30, 'Denied')], default=10)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
