# Generated by Django 3.0.7 on 2020-07-13 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0074_auto_20200713_0637'),
        ('users', '0002_auto_20200617_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='me2ushop.Address'),
        ),
    ]
