# Generated by Django 3.1.1 on 2020-10-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_sellerprofile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='image',
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='subscription_type',
            field=models.CharField(choices=[('Bs', 'Basic'), ('Pr', 'Premium')], help_text='Select a monthly recurring subscription fees', max_length=2),
        ),
    ]
