# Generated by Django 3.0.7 on 2020-07-13 11:50

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_user_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_address',
        ),
        migrations.AddField(
            model_name='profile',
            name='address_type',
            field=models.CharField(choices=[('B', 'Billing'), ('S', 'Shipping')], default='B', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='apartment_address',
            field=models.CharField(default='highrise', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(default='ke', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='payment_option',
            field=models.CharField(default='mpesa', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='street_address',
            field=models.CharField(default='mbagathi', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='zip',
            field=models.CharField(default='00100', max_length=10),
            preserve_default=False,
        ),
    ]
