# Generated by Django 3.1.1 on 2020-10-30 12:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201030_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='business_title',
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='creation date and time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='modified',
            field=models.DateTimeField(editable=False, null=True, verbose_name='modification date and time'),
        ),
    ]
