# Generated by Django 3.0.7 on 2020-08-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200830_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobile_profile',
            name='application_status',
            field=models.CharField(choices=[(10, 'Under Review'), (20, 'Accepted'), (30, 'Denied')], default=10, max_length=2),
        ),
        migrations.AddField(
            model_name='seller_profile',
            name='application_status',
            field=models.CharField(choices=[(10, 'Under Review'), (20, 'Accepted'), (30, 'Denied')], default=10, max_length=2),
        ),
    ]
