# Generated by Django 3.1.1 on 2021-01-22 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210122_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellerprofile',
            old_name='facebook_page',
            new_name='facebook',
        ),
    ]
