# Generated by Django 3.0.7 on 2020-07-19 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200713_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address_type',
            field=models.CharField(choices=[('B', 'Billing'), ('S', 'Shipping'), ('T', 'Both')], max_length=1),
        ),
    ]
