# Generated by Django 3.0.7 on 2020-08-31 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200830_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomobileProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('passport_no', models.CharField(max_length=20)),
                ('automobile_type', models.CharField(choices=[('Cr', 'Car'), ('Pk', 'Pick Up'), ('Va', 'Van'), ('Bs', 'Bus'), ('Tr', 'Truck'), ('Mt', 'Motor'), ('Bc', 'Bicycle')], max_length=4)),
                ('date_of_registration', models.DateTimeField(auto_now_add=True)),
                ('country', models.CharField(choices=[('KE', 'Kenya'), ('UG', 'Uganda'), ('TZ', 'Tanzania'), ('RW', 'Rwanda')], max_length=2)),
                ('city_of_operation', models.CharField(choices=[('Kg', 'Kigali'), ('Kp', 'Kampala'), ('Nb', 'Nairobi'), ('Dd', 'Dodoma')], max_length=2)),
                ('application_status', models.IntegerField(choices=[(10, 'Under Review'), (20, 'Accepted'), (30, 'Denied')], default=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('business_type', models.CharField(choices=[('Co', 'Company'), ('Sol', 'Sole Proprietorship')], max_length=4)),
                ('business_title', models.CharField(max_length=30)),
                ('tax_country', django_countries.fields.CountryField(max_length=2)),
                ('subscription_type', models.CharField(choices=[('Bs', 'Basic'), ('Pr', 'Premium')], max_length=2)),
                ('application_status', models.IntegerField(choices=[(10, 'Under Review'), (20, 'Accepted'), (30, 'Denied')], default=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='seller_profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Automobile_Profile',
        ),
        migrations.DeleteModel(
            name='Seller_Profile',
        ),
    ]
