# Generated by Django 3.0.7 on 2020-07-19 08:05

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200719_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=stdimage.models.StdImageField(blank=True, default='default.svg', null=True, upload_to='profile_pics'),
        ),
    ]
