# Generated by Django 3.1.1 on 2020-09-15 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='seller',
        ),
    ]
