# Generated by Django 3.1.1 on 2021-01-24 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_sellerprofile_business_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobileprofile',
            name='application_status',
            field=models.IntegerField(choices=[(10, 'Under Review'), (20, 'Active'), (30, 'Denied'), (40, 'Blocked')], default=10),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='application_status',
            field=models.IntegerField(choices=[(10, 'Under Review'), (20, 'Active'), (30, 'Denied'), (40, 'Blocked')], default=10),
        ),
    ]
