# Generated by Django 3.1.1 on 2021-01-28 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='business_description',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='business_type',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='subscription_type',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='telegram',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='website_link',
        ),
    ]
