# Generated by Django 3.1.1 on 2021-01-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210128_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='middle_name',
            field=models.CharField(blank=True, help_text='Provide official Middle name on passport or ID', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='first_name',
            field=models.CharField(help_text='Provide official First name on passport or ID', max_length=15),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='last_name',
            field=models.CharField(help_text='Provide official Last name on passport or ID', max_length=15),
        ),
    ]
