# Generated by Django 3.1.1 on 2021-01-28 21:58

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210128_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='verification_id',
            field=stdimage.models.StdImageField(blank=True, help_text='Upload your ID/Passport', null=True, upload_to='images/sellerID'),
        ),
    ]
