# Generated by Django 3.1.1 on 2021-01-29 09:02

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_sellerprofile_verification_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobileprofile',
            name='application_status',
            field=models.IntegerField(choices=[(10, 'Under Review'), (20, 'Active'), (30, 'Verified'), (40, 'Denied'), (50, 'Blocked')], default=10),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='application_status',
            field=models.IntegerField(choices=[(10, 'Under Review'), (20, 'Active'), (30, 'Verified'), (40, 'Denied'), (50, 'Blocked')], default=10),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='verification_id',
            field=stdimage.models.StdImageField(help_text='Upload your ID/Passport', upload_to='images/sellerID'),
        ),
    ]
