# Generated by Django 3.1.1 on 2021-05-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20210129_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='created',
            field=models.DateTimeField(editable=False, null=True, verbose_name='creation date and time'),
        ),
    ]
