# Generated by Django 3.1.1 on 2021-06-04 17:57

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20210520_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, help_text='Provide official First name on passport or ID', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, help_text='Provide official Last name on passport or ID', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='middle_name',
            field=models.CharField(blank=True, help_text='Provide official Middle name on passport or ID', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_id',
            field=stdimage.models.StdImageField(blank=True, help_text='Upload your ID/Passport', null=True, upload_to='images/sellerID'),
        ),
    ]
