# Generated by Django 3.1.1 on 2021-05-24 23:03

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20210520_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
