# Generated by Django 3.1.1 on 2021-05-25 02:29

from django.db import migrations, models
import django_countries.fields
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20210525_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automobileprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='BusinessInformation',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, help_text='Provide official First name on passport or ID', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, help_text='Provide official Last name on passport or ID', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='middle_name',
            field=models.CharField(blank=True, help_text='Provide official Middle name on passport or ID', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_id',
            field=stdimage.models.StdImageField(blank=True, help_text='Upload your ID/Passport to receive a verified badge', null=True, upload_to='images/sellerID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, help_text='This number will be visible Start with country code . i.e +250 785011413', max_length=20, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='AutomobileProfile',
        ),
        migrations.DeleteModel(
            name='SellerProfile',
        ),
    ]
