# Generated by Django 3.1.1 on 2021-06-18 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_delete_sellerprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessInformation',
        ),
    ]
