# Generated by Django 3.1.1 on 2021-10-28 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_delete_businessinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
