# Generated by Django 3.1.1 on 2021-11-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_profile_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_url',
            field=models.CharField(blank=True, help_text='Image Url has higher precedence as compared to the Image field below!', max_length=500, null=True),
        ),
    ]
