# Generated by Django 3.0.7 on 2020-07-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20200709_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productview',
            name='tracking_id',
            field=models.CharField(default='', max_length=70),
        ),
    ]
