# Generated by Django 3.1.1 on 2021-07-19 14:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0116_auto_20210701_0405'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stats', '0003_contactview'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactView',
            new_name='BrandView',
        ),
    ]
