# Generated by Django 3.0.7 on 2020-07-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_auto_20200709_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='productview',
            name='valid_tracker',
            field=models.BooleanField(default=True),
        ),
    ]
