# Generated by Django 3.0.7 on 2020-07-17 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_productview_valid_tracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productview',
            name='tracking_id',
            field=models.CharField(max_length=70),
        ),
    ]
