# Generated by Django 3.1.1 on 2020-12-15 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketing', '0001_initial'),
        ('me2ushop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trend',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='me2ushop.product'),
        ),
        migrations.AddField(
            model_name='slider',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='me2ushop.product'),
        ),
        migrations.AddField(
            model_name='deals',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='me2ushop.product'),
        ),
        migrations.AddField(
            model_name='banner',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='me2ushop.product'),
        ),
    ]
