# Generated by Django 3.1.1 on 2020-10-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_auto_20201007_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='banner_discount_price',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=9),
            preserve_default=False,
        ),
    ]
