# Generated by Django 3.1.1 on 2021-01-24 05:11

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_auto_20210124_0533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='featured',
            new_name='is_deal',
        ),
        migrations.AddField(
            model_name='trend',
            name='image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='images/marketing/banner'),
        ),
        migrations.DeleteModel(
            name='Deals',
        ),
    ]
