# Generated by Django 3.1.1 on 2020-10-07 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_banner_banner_discount_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deals',
            old_name='discount_price',
            new_name='deal_discount_price',
        ),
    ]
