# Generated by Django 3.1.1 on 2020-10-07 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_auto_20201007_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deals',
            name='is_on_offer',
        ),
    ]
