# Generated by Django 3.1.1 on 2020-10-08 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_remove_deals_is_on_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
