# Generated by Django 3.1.1 on 2020-10-08 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0012_auto_20201008_0355'),
        ('marketing', '0006_banner_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='image_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='me2ushop.product'),
        ),
    ]
