# Generated by Django 3.1.1 on 2021-04-11 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0006_auto_20210411_1853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketingmessage',
            options={'ordering': ['end_date']},
        ),
    ]
