# Generated by Django 3.1.1 on 2020-10-08 02:09

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0007_auto_20201008_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='background_image_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='images/marketing/slider'),
        ),
    ]
