# Generated by Django 3.1.1 on 2021-04-11 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0007_auto_20210411_2051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketingmessage',
            options={'ordering': ['-end_date']},
        ),
    ]
