# Generated by Django 3.1.1 on 2020-10-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0008_auto_20201008_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='bestselling',
            field=models.BooleanField(default=False),
        ),
    ]
