# Generated by Django 3.1.1 on 2020-10-08 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0009_banner_bestselling'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='banner_product_name',
            new_name='product',
        ),
    ]
