# Generated by Django 3.1.1 on 2020-10-08 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0010_auto_20201008_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingemails',
            name='subscribed',
            field=models.BooleanField(default=True),
        ),
    ]
