# Generated by Django 3.1.1 on 2020-10-08 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0011_marketingemails_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
    ]
