# Generated by Django 3.1.1 on 2020-10-08 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0012_banner_is_trending'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='banner_header',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
