# Generated by Django 3.1.1 on 2020-10-09 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0013_auto_20201009_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='top_display',
            field=models.BooleanField(default=False),
        ),
    ]
