# Generated by Django 3.1.1 on 2020-11-08 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0015_deals_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deals',
            name='image',
        ),
        migrations.RemoveField(
            model_name='deals',
            name='link_url',
        ),
    ]
