# Generated by Django 3.1.1 on 2020-11-08 17:10

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0046_auto_20201108_1910'),
        ('marketing', '0016_auto_20201108_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, verbose_name='creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='modification date and time')),
                ('trend_background', stdimage.models.StdImageField(blank=True, null=True, upload_to='images/marketing/trends')),
                ('trend_text', models.CharField(max_length=200)),
                ('trend_header', models.CharField(max_length=120)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='me2ushop.product')),
            ],
            options={
                'ordering': ['-start_date', '-end_date'],
            },
        ),
    ]
