# Generated by Django 3.1.1 on 2020-11-08 18:56

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0017_trend'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, verbose_name='creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='modification date and time')),
                ('trend_background', stdimage.models.StdImageField(blank=True, null=True, upload_to='images/marketing/trends')),
                ('trend_text', models.CharField(max_length=200)),
                ('trend_header', models.CharField(max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='trend',
            name='trend_background',
        ),
        migrations.RemoveField(
            model_name='trend',
            name='trend_header',
        ),
        migrations.RemoveField(
            model_name='trend',
            name='trend_text',
        ),
        migrations.AddField(
            model_name='trend',
            name='trend_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.trendinfo'),
        ),
    ]
