# Generated by Django 3.1.1 on 2020-11-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0018_auto_20201108_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trendinfo',
            name='trend_text',
            field=models.TextField(max_length=300),
        ),
    ]
