# Generated by Django 3.1.1 on 2020-11-08 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0019_auto_20201108_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trend',
            name='trend_info',
        ),
    ]
