# Generated by Django 3.1.1 on 2021-10-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0020_faq_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='is_bestrated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='banner',
            name='is_bestseller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='banner',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
