# Generated by Django 3.1.1 on 2020-11-25 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0022_auto_20201125_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='banner_discount_price',
        ),
    ]
