# Generated by Django 3.1.1 on 2020-11-25 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0023_remove_banner_banner_discount_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='image',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='link_url',
        ),
    ]
