# Generated by Django 3.1.1 on 2021-02-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210220_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click Below To Read Blog Post...', max_length=255),
        ),
    ]
