# Generated by Django 3.1.1 on 2021-02-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click Below To Read Blog Post...', help_text='This is what USERS/READERS who have NOT SIGNED in will see. Make them login to read your article by capturing their attention', max_length=255),
        ),
    ]
