# Generated by Django 3.1.1 on 2021-02-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210223_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default='I love it'),
            preserve_default=False,
        ),
    ]
