# Generated by Django 3.1.1 on 2021-03-20 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_comment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
