# Generated by Django 3.1.1 on 2021-03-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_remove_comment_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created'], 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click Below To Read Blog Post...', help_text='This is what USERS/READERS who have NOT SIGNED in will see. Make them login to read your article by capturing their attention. What is your post about', max_length=350),
        ),
    ]
