# Generated by Django 3.0.7 on 2020-08-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0003_auto_20200808_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('S', 'Stripe'), ('C', 'Cash On Delivery'), ('M', 'M-Pesa'), ('P', 'Paypal'), ('D', 'Debit Card')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(default='admin', help_text='Your store name', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_description',
            field=models.CharField(help_text='help sellers get your product easily. Give a simple short description about the page content you have added', max_length=255, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_keywords',
            field=models.CharField(help_text='Comma-delimited set of SEO keywords that summarize the type of product above max 4 words', max_length=100, verbose_name='Meta Keywords'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(help_text='Unique value for product page URL, created from the product title.', unique=True),
        ),
    ]
