# Generated by Django 3.0.7 on 2020-08-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0004_auto_20200830_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('S', 'Stripe'), ('D', 'Debit Card'), ('C', 'Cash On Delivery'), ('P', 'Paypal'), ('M', 'M-Pesa')], max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='cart_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='cart_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
