# Generated by Django 3.0.7 on 2020-08-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0004_auto_20200811_0848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='old_price',
            new_name='discount_price',
        ),
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('S', 'Stripe'), ('C', 'Cash On Delivery'), ('P', 'Paypal'), ('D', 'Debit Card'), ('M', 'M-Pesa')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.CharField(blank=True, choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], help_text='tags the product NEW upon upload for the next 24 hoursprimary blue, danger red, secondary purple', max_length=1, null=True),
        ),
    ]
