# Generated by Django 3.0.7 on 2020-08-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0005_auto_20200816_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='date_ordered',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('D', 'Debit Card'), ('C', 'Cash On Delivery'), ('M', 'M-Pesa'), ('P', 'Paypal'), ('S', 'Stripe')], max_length=2),
        ),
    ]
