# Generated by Django 3.1.1 on 2020-10-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0005_auto_20201007_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('P', 'Paypal'), ('C', 'Cash On Delivery'), ('S', 'Stripe'), ('M', 'M-Pesa'), ('D', 'Debit Card')], max_length=2),
        ),
    ]
