# Generated by Django 3.0.7 on 2020-08-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0006_auto_20200830_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('C', 'Cash On Delivery'), ('P', 'Paypal'), ('D', 'Debit Card'), ('M', 'M-Pesa'), ('S', 'Stripe')], max_length=2),
        ),
    ]
