# Generated by Django 3.0.7 on 2020-08-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0006_auto_20200818_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('S', 'Stripe'), ('P', 'Paypal'), ('C', 'Cash On Delivery'), ('M', 'M-Pesa'), ('D', 'Debit Card')], max_length=2),
        ),
    ]
