# Generated by Django 3.1.1 on 2020-10-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0007_auto_20201008_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_bestrated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('S', 'Stripe'), ('M', 'M-Pesa'), ('C', 'Cash On Delivery'), ('D', 'Debit Card'), ('P', 'Paypal')], max_length=2),
        ),
    ]
