# Generated by Django 3.0.7 on 2020-08-19 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0007_auto_20200818_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('M', 'M-Pesa'), ('C', 'Cash On Delivery'), ('D', 'Debit Card'), ('P', 'Paypal'), ('S', 'Stripe')], max_length=2),
        ),
    ]
