# Generated by Django 3.0.7 on 2020-08-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0007_auto_20200830_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('S', 'Stripe'), ('M', 'M-Pesa'), ('D', 'Debit Card'), ('C', 'Cash On Delivery'), ('P', 'Paypal')], max_length=2),
        ),
    ]
