# Generated by Django 3.0.7 on 2020-08-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0008_auto_20200819_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('P', 'Paypal'), ('D', 'Debit Card'), ('M', 'M-Pesa'), ('C', 'Cash On Delivery'), ('S', 'Stripe')], max_length=2),
        ),
    ]
