# Generated by Django 3.1.1 on 2020-10-08 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0008_auto_20201008_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('P', 'Paypal'), ('D', 'Debit Card'), ('C', 'Cash On Delivery'), ('M', 'M-Pesa'), ('S', 'Stripe')], max_length=2),
        ),
    ]
