# Generated by Django 3.1.1 on 2021-01-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0009_auto_20210123_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('P', 'Paypal'), ('M', 'M-Pesa'), ('D', 'Debit Card'), ('C', 'Cash On Delivery'), ('S', 'Stripe')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('N', 'New'), ('R', 'Refurbished'), ('U', 'Used'), ('C', 'Certified')], help_text='Choose the current condition for the product', max_length=2),
        ),
    ]
