# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-27 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0009_item_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
    ]
