# Generated by Django 3.1.1 on 2021-01-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('me2ushop', '0010_auto_20210123_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('D', 'Debit Card'), ('M', 'M-Pesa'), ('P', 'Paypal'), ('S', 'Stripe'), ('C', 'Cash On Delivery')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('N', 'New'), ('U', 'Used'), ('R', 'Refurbished'), ('C', 'Certified')], help_text='Choose the current condition for the product', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_categories',
            field=models.ManyToManyField(help_text='Check the box of the category where your product belongs. Please note that different categories attract different Ad charges. Be specific to one or two categories where your product belongs on the provided tree. Contact us for help', to='categories.Department'),
        ),
    ]
