# Generated by Django 3.0.7 on 2020-08-30 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0011_auto_20200830_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('C', 'Cash On Delivery'), ('M', 'M-Pesa'), ('P', 'Paypal'), ('S', 'Stripe'), ('D', 'Debit Card')], max_length=2),
        ),
    ]
