# Generated by Django 3.1.1 on 2020-10-08 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0011_auto_20201008_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('M', 'M-Pesa'), ('P', 'Paypal'), ('C', 'Cash On Delivery'), ('S', 'Stripe'), ('D', 'Debit Card')], max_length=2),
        ),
    ]
