# Generated by Django 3.0.7 on 2020-08-31 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0012_auto_20200830_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('S', 'Stripe'), ('M', 'M-Pesa'), ('C', 'Cash On Delivery'), ('P', 'Paypal'), ('D', 'Debit Card')], max_length=2),
        ),
    ]
