# Generated by Django 3.1.1 on 2020-09-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0013_auto_20200831_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('C', 'Cash On Delivery'), ('P', 'Paypal'), ('D', 'Debit Card'), ('S', 'Stripe'), ('M', 'M-Pesa')], max_length=2),
        ),
    ]
