# Generated by Django 3.1.1 on 2020-09-14 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0015_auto_20200908_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('M', 'M-Pesa'), ('D', 'Debit Card'), ('P', 'Paypal'), ('C', 'Cash On Delivery'), ('S', 'Stripe')], max_length=2),
        ),
    ]
