# Generated by Django 3.1.1 on 2021-01-26 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0015_auto_20210125_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('P', 'Paypal'), ('C', 'Cash On Delivery'), ('M', 'M-Pesa'), ('S', 'Stripe'), ('D', 'Debit Card')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('C', 'Certified'), ('N', 'New'), ('U', 'Used'), ('R', 'Refurbished')], help_text='Choose the current condition for the product', max_length=2),
        ),
    ]
