# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-29 06:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0016_auto_20200529_0730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordered_date',
            new_name='order_date',
        ),
    ]
