# Generated by Django 3.1.1 on 2021-01-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0016_auto_20210126_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('D', 'Debit Card'), ('C', 'Cash On Delivery'), ('P', 'Paypal'), ('M', 'M-Pesa'), ('S', 'Stripe')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('R', 'Refurbished'), ('U', 'Used'), ('C', 'Certified'), ('N', 'New')], help_text='Choose the current condition for the product', max_length=2),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='in_display',
            field=models.BooleanField(default=False),
        ),
    ]
