# Generated by Django 3.1.1 on 2020-10-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0016_auto_20201008_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('D', 'Debit Card'), ('P', 'Paypal'), ('S', 'Stripe'), ('M', 'M-Pesa'), ('C', 'Cash On Delivery')], max_length=2),
        ),
    ]
