# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-29 16:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0017_auto_20200529_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripepayment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
