# Generated by Django 3.1.1 on 2020-10-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0017_auto_20201008_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_link_url',
            new_name='image_url',
        ),
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('P', 'Paypal'), ('D', 'Debit Card'), ('S', 'Stripe'), ('M', 'M-Pesa'), ('C', 'Cash On Delivery')], max_length=2),
        ),
    ]
