# Generated by Django 3.1.1 on 2020-09-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0017_auto_20200915_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('P', 'Paypal'), ('M', 'M-Pesa'), ('C', 'Cash On Delivery'), ('D', 'Debit Card'), ('S', 'Stripe')], max_length=2),
        ),
    ]
