# Generated by Django 3.1.1 on 2020-09-17 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0018_auto_20200916_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('S', 'Stripe'), ('P', 'Paypal'), ('C', 'Cash On Delivery'), ('D', 'Debit Card'), ('M', 'M-Pesa')], max_length=2),
        ),
    ]
