# Generated by Django 3.1.1 on 2020-10-08 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0019_auto_20201008_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('C', 'Cash On Delivery'), ('P', 'Paypal'), ('S', 'Stripe'), ('M', 'M-Pesa'), ('D', 'Debit Card')], max_length=2),
        ),
    ]
