# Generated by Django 3.1.1 on 2021-01-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0019_auto_20210127_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('M', 'M-Pesa'), ('S', 'Stripe'), ('P', 'Paypal'), ('C', 'Cash On Delivery'), ('D', 'Debit Card')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('N', 'New'), ('R', 'Refurbished'), ('U', 'Used'), ('C', 'Certified')], help_text='Choose the current condition for the product', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='', editable=False, help_text='Unique value for product page URL, created from the product title.', unique=True),
        ),
    ]
