# Generated by Django 3.1.1 on 2020-10-08 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0020_auto_20201009_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('M', 'M-Pesa'), ('D', 'Debit Card'), ('S', 'Stripe'), ('P', 'Paypal'), ('C', 'Cash On Delivery')], max_length=2),
        ),
    ]
