# Generated by Django 3.1.1 on 2020-10-09 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0021_auto_20201009_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('S', 'Stripe'), ('D', 'Debit Card'), ('M', 'M-Pesa'), ('C', 'Cash On Delivery'), ('P', 'Paypal')], max_length=2),
        ),
    ]
