# Generated by Django 3.1.1 on 2021-01-28 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('me2ushop', '0021_auto_20210128_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_category',
            field=models.ForeignKey(blank=True, help_text="Choose the main Category for the product.It's free", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_choice', to='categories.department'),
        ),
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('P', 'Paypal'), ('S', 'Stripe'), ('D', 'Debit Card'), ('M', 'M-Pesa'), ('C', 'Cash On Delivery')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('R', 'Refurbished'), ('U', 'Used'), ('N', 'New'), ('C', 'Certified')], help_text='Choose the current condition for the product', max_length=2),
        ),
    ]
