# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-30 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0022_auto_20200530_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
