# Generated by Django 3.1.1 on 2021-01-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0022_auto_20210128_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_choice',
        ),
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('M', 'M-Pesa'), ('C', 'Cash On Delivery'), ('D', 'Debit Card'), ('S', 'Stripe'), ('P', 'Paypal')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('N', 'New'), ('U', 'Used'), ('C', 'Certified'), ('R', 'Refurbished')], help_text='Choose the current condition for the product', max_length=2),
        ),
    ]
