# Generated by Django 3.1.1 on 2020-10-13 01:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0023_auto_20201010_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='creation date and time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productimage',
            name='modified',
            field=models.DateTimeField(editable=False, null=True, verbose_name='modification date and time'),
        ),
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('M', 'M-Pesa'), ('S', 'Stripe'), ('P', 'Paypal'), ('C', 'Cash On Delivery'), ('D', 'Debit Card')], max_length=2),
        ),
    ]
