# Generated by Django 3.1.1 on 2020-10-14 13:34

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0025_auto_20201014_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='images/brands/brand_background'),
        ),
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='images/brands/brand_logo'),
        ),
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('M', 'M-Pesa'), ('P', 'Paypal'), ('C', 'Cash On Delivery'), ('D', 'Debit Card'), ('S', 'Stripe')], max_length=2),
        ),
    ]
