# Generated by Django 3.1.1 on 2021-01-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0025_auto_20210128_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('D', 'Debit Card'), ('S', 'Stripe'), ('C', 'Cash On Delivery'), ('P', 'Paypal'), ('M', 'M-Pesa')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('R', 'Refurbished'), ('N', 'New'), ('C', 'Certified'), ('U', 'Used')], help_text='Choose the current condition for the product', max_length=2),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='attribute',
            field=models.CharField(max_length=50),
        ),
    ]
