# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-31 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0025_auto_20200531_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantityOrder',
        ),
    ]
