# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-31 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0026_remove_item_quantityorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='me2ushop.QuantityCart'),
        ),
    ]
