# Generated by Django 3.1.1 on 2020-10-14 14:41

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0026_auto_20201014_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('M', 'M-Pesa'), ('D', 'Debit Card'), ('C', 'Cash On Delivery'), ('S', 'Stripe'), ('P', 'Paypal')], max_length=2),
        ),
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=stdimage.models.StdImageField(blank=True, help_text='wallpaper for your store', null=True, upload_to='images/brands/brand_background'),
        ),
    ]
