# Generated by Django 3.1.1 on 2021-01-28 21:46

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0026_auto_20210128_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='business_description',
            field=models.TextField(blank=True, help_text='Tell us what you do and the kind of products you sell', null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='business_type',
            field=models.CharField(blank=True, choices=[('Co', 'Company'), ('Sol', 'Sole Proprietorship')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='facebook',
            field=models.CharField(blank=True, help_text='Do you have a facebook page. Copy paste your page link here e.g.. https://www.facebook.com/Me2UAfrika', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='instagram',
            field=models.CharField(blank=True, help_text='Do you have a instagram page. Copy paste your page link here eg. https://www.instagram.com/me2u_afrika/', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='subscription_type',
            field=models.CharField(blank=True, choices=[('Fr', 'Free'), ('Bs', 'Basic'), ('Pr', 'Premium')], help_text='Select a monthly recurring subscription fees', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='telegram',
            field=models.CharField(blank=True, help_text='Do you have a Telegram Channel. Copy paste your page link here. e.g.. https://t.me/me2uafrika', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='website_link',
            field=models.CharField(blank=True, help_text='If you have a website by which buyers can find out more about your services.e.g. https://www.facebook.com', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('S', 'Stripe'), ('M', 'M-Pesa'), ('D', 'Debit Card'), ('C', 'Cash On Delivery'), ('P', 'Paypal')], max_length=2),
        ),
        migrations.AlterField(
            model_name='brand',
            name='title',
            field=models.CharField(help_text='Unique business title to identify Your store and your product line', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('C', 'Certified'), ('U', 'Used'), ('R', 'Refurbished'), ('N', 'New')], help_text='Choose the current condition for the product', max_length=2),
        ),
    ]
