# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-01 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0030_item_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='stripe_payment',
            new_name='payment',
        ),
        migrations.AddField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default='1234ABCD', max_length=20),
            preserve_default=False,
        ),
    ]
