# Generated by Django 3.1.1 on 2021-01-28 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_sellerprofile_verification_id'),
        ('me2ushop', '0031_auto_20210129_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('M', 'M-Pesa'), ('S', 'Stripe'), ('P', 'Paypal'), ('C', 'Cash On Delivery'), ('D', 'Debit Card')], max_length=2),
        ),
        migrations.AlterField(
            model_name='brand',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.sellerprofile'),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('U', 'Used'), ('N', 'New'), ('R', 'Refurbished')], help_text='Choose the current condition for the product', max_length=2),
        ),
    ]
