# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-03 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0031_auto_20200601_0556'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestRefund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('accepted', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='me2ushop.Order')),
            ],
        ),
    ]
