# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-03 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0032_requestrefund'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestrefund',
            name='email',
            field=models.EmailField(default='danielmakori0@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
