# Generated by Django 3.1.1 on 2020-10-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0032_auto_20201017_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('P', 'Paypal'), ('C', 'Cash On Delivery'), ('D', 'Debit Card'), ('M', 'M-Pesa'), ('S', 'Stripe')], max_length=2),
        ),
    ]
