# Generated by Django 3.1.1 on 2021-01-28 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0032_auto_20210129_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('S', 'Stripe'), ('P', 'Paypal'), ('C', 'Cash On Delivery'), ('M', 'M-Pesa'), ('D', 'Debit Card')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('N', 'New'), ('U', 'Used'), ('R', 'Refurbished')], help_text='Choose the current condition for the product', max_length=2),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='in_display',
            field=models.BooleanField(default=True),
        ),
    ]
