# Generated by Django 3.1.1 on 2021-01-29 09:02

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0033_auto_20210129_0150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ('-in_display',)},
        ),
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('P', 'Paypal'), ('D', 'Debit Card'), ('C', 'Cash On Delivery'), ('M', 'M-Pesa'), ('S', 'Stripe')], max_length=2),
        ),
        migrations.AlterField(
            model_name='brand',
            name='business_description',
            field=models.TextField(help_text='Tell us what you do and the kind of products you sell'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='business_type',
            field=models.CharField(choices=[('Co', 'Company'), ('Sol', 'Sole Proprietorship/Personal')], max_length=4),
        ),
        migrations.AlterField(
            model_name='brand',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='brand',
            name='subscription_type',
            field=models.CharField(choices=[('Fr', 'Free'), ('Bs', 'Basic'), ('Pr', 'Premium')], help_text='Select a monthly recurring subscription fees', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('U', 'Used'), ('N', 'New'), ('R', 'Refurbished')], help_text='Choose the current condition for the product', max_length=2),
        ),
    ]
