# Generated by Django 3.1.1 on 2021-01-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0034_auto_20210129_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('P', 'Paypal'), ('C', 'Cash On Delivery'), ('S', 'Stripe'), ('D', 'Debit Card'), ('M', 'M-Pesa')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('R', 'Refurbished'), ('U', 'Used'), ('N', 'New')], help_text='Choose the current condition for the product', max_length=2),
        ),
    ]
