# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-03 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0035_auto_20200603_1947'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BillingAddress',
            new_name='Address',
        ),
    ]
