# Generated by Django 3.1.1 on 2020-10-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0035_auto_20201023_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='added_to_wishlist',
            new_name='added',
        ),
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('M', 'M-Pesa'), ('S', 'Stripe'), ('P', 'Paypal'), ('C', 'Cash On Delivery'), ('D', 'Debit Card')], max_length=2),
        ),
    ]
