# Generated by Django 3.1.1 on 2020-10-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0037_auto_20201023_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('P', 'Paypal'), ('D', 'Debit Card'), ('S', 'Stripe'), ('M', 'M-Pesa'), ('C', 'Cash On Delivery')], max_length=2),
        ),
    ]
