# Generated by Django 3.1.1 on 2020-10-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0038_auto_20201029_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('D', 'Debit Card'), ('P', 'Paypal'), ('M', 'M-Pesa'), ('S', 'Stripe'), ('C', 'Cash On Delivery')], max_length=2),
        ),
    ]
