# Generated by Django 3.1.1 on 2021-02-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0038_auto_20210129_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('M', 'M-Pesa'), ('D', 'Debit Card'), ('C', 'Cash On Delivery'), ('S', 'Stripe'), ('P', 'Paypal')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='additional_information',
            field=models.TextField(blank=True, help_text='Provide additional information about your product. Buyers mostly buy from well detailed products and specifications', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('R', 'Refurbished'), ('N', 'New'), ('U', 'Used')], help_text='Choose the current condition for the product', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_description',
            field=models.CharField(help_text="Give a simple short description on the information you have provided on the page this page. i.e This product is used for cleaning, cooking and it was recently released by it's manufacturer. Google uses this keywords and description to index your product for it to be found easily ", max_length=255, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_keywords',
            field=models.CharField(help_text='Comma-delimited set of SEO keywords that summarize the type of product above max 4 words. This keywords will help buyers find your product easily. Read more https://ads.google.com/home/tools/keyword-planner/', max_length=100, verbose_name='Meta Keywords'),
        ),
    ]
