# Generated by Django 3.1.1 on 2020-10-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0039_auto_20201030_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('C', 'Cash On Delivery'), ('D', 'Debit Card'), ('S', 'Stripe'), ('M', 'M-Pesa'), ('P', 'Paypal')], max_length=2),
        ),
        migrations.AlterField(
            model_name='brand',
            name='title',
            field=models.CharField(help_text='Unique title to identify Your store and your product line', max_length=100, unique=True),
        ),
    ]
