# Generated by Django 3.1.1 on 2020-11-02 22:14

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0040_auto_20201030_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('M', 'M-Pesa'), ('D', 'Debit Card'), ('P', 'Paypal'), ('S', 'Stripe'), ('C', 'Cash On Delivery')], max_length=2),
        ),
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=stdimage.models.StdImageField(blank=True, default='images/brands/brand_background/default.jpg', help_text="wallpaper for your store.Leave blank if you don't have one", null=True, upload_to='images/brands/brand_background'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=stdimage.models.StdImageField(blank=True, help_text="logo for your store, Leave blank if you don't have one", null=True, upload_to='images/brands/brand_logo'),
        ),
    ]
