# Generated by Django 3.1.1 on 2020-11-05 07:56

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0041_auto_20201103_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('D', 'Debit Card'), ('M', 'M-Pesa'), ('P', 'Paypal'), ('S', 'Stripe'), ('C', 'Cash On Delivery')], max_length=2),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=stdimage.models.StdImageField(upload_to='images/products'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='me2ushop.product'),
        ),
    ]
