# Generated by Django 3.1.1 on 2020-11-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0042_auto_20201105_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='is_featured',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('C', 'Cash On Delivery'), ('S', 'Stripe'), ('M', 'M-Pesa'), ('P', 'Paypal'), ('D', 'Debit Card')], max_length=2),
        ),
    ]
