# Generated by Django 3.1.1 on 2021-02-04 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0042_auto_20210204_0251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='made_in_afrika',
        ),
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('D', 'Debit Card'), ('S', 'Stripe'), ('P', 'Paypal'), ('C', 'Cash On Delivery'), ('M', 'M-Pesa')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('N', 'New'), ('R', 'Refurbished'), ('U', 'Used')], help_text='Choose the current condition for the product', max_length=2),
        ),
    ]
