# Generated by Django 3.1.1 on 2020-11-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0043_auto_20201108_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('D', 'Debit Card'), ('C', 'Cash On Delivery'), ('M', 'M-Pesa'), ('S', 'Stripe'), ('P', 'Paypal')], max_length=2),
        ),
    ]
