# Generated by Django 3.0.7 on 2020-06-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('me2ushop', '0044_auto_20200622_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='category',
            new_name='category_choice',
        ),
        migrations.AddField(
            model_name='item',
            name='product_categories',
            field=models.ManyToManyField(to='categories.Category'),
        ),
    ]
