# Generated by Django 3.1.1 on 2020-11-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0044_auto_20201108_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('S', 'Stripe'), ('C', 'Cash On Delivery'), ('M', 'M-Pesa'), ('P', 'Paypal'), ('D', 'Debit Card')], max_length=2),
        ),
    ]
