# Generated by Django 3.0.7 on 2020-06-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0045_auto_20200622_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=9),
        ),
        migrations.AlterField(
            model_name='stripepayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
