# Generated by Django 3.0.7 on 2020-06-23 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('me2ushop', '0046_auto_20200623_1714'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Product',
        ),
    ]
