# Generated by Django 3.1.1 on 2020-11-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0046_auto_20201108_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('M', 'M-Pesa'), ('P', 'Paypal'), ('S', 'Stripe'), ('D', 'Debit Card'), ('C', 'Cash On Delivery')], max_length=2),
        ),
    ]
