# Generated by Django 3.1.1 on 2020-11-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0047_auto_20201108_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('D', 'Debit Card'), ('P', 'Paypal'), ('M', 'M-Pesa'), ('C', 'Cash On Delivery'), ('S', 'Stripe')], max_length=2),
        ),
    ]
