# Generated by Django 3.1.1 on 2021-02-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0047_auto_20210218_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('D', 'Debit Card'), ('C', 'Cash On Delivery'), ('P', 'Paypal'), ('S', 'Stripe'), ('M', 'M-Pesa')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('R', 'Refurbished'), ('U', 'Used'), ('N', 'New')], help_text='Choose the current condition for the product', max_length=2),
        ),
    ]
