# Generated by Django 3.1.1 on 2020-11-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0048_auto_20201108_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('M', 'M-Pesa'), ('C', 'Cash On Delivery'), ('S', 'Stripe'), ('D', 'Debit Card'), ('P', 'Paypal')], max_length=2),
        ),
    ]
