# Generated by Django 3.1.1 on 2021-02-20 13:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0050_auto_20210220_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('M', 'M-Pesa'), ('S', 'Stripe'), ('C', 'Cash On Delivery'), ('D', 'Debit Card'), ('P', 'Paypal')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='additional_information',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Provide additional information about your product. Buyers mostly buy from well detailed products and specifications', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('N', 'New'), ('R', 'Refurbished'), ('U', 'Used')], help_text='Choose the current condition for the product', max_length=2),
        ),
    ]
