# Generated by Django 3.0.7 on 2020-06-30 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0051_delete_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='me2ushop.OrderItem'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cart_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='items', to='me2ushop.OrderItem'),
        ),
    ]
