# Generated by Django 3.0.7 on 2020-06-30 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0052_auto_20200630_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='cart_ref',
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='me2ushop.OrderItem'),
        ),
        migrations.AddField(
            model_name='order',
            name='cart_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='me2ushop.CartID'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='cart_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='me2ushop.CartID'),
        ),
    ]
