# Generated by Django 3.1.1 on 2020-11-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0052_auto_20201109_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_on_offer',
        ),
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('C', 'Cash On Delivery'), ('M', 'M-Pesa'), ('S', 'Stripe'), ('D', 'Debit Card'), ('P', 'Paypal')], max_length=2),
        ),
    ]
