# Generated by Django 3.1.1 on 2020-11-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0053_auto_20201109_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='label',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('M', 'M-Pesa'), ('D', 'Debit Card'), ('C', 'Cash On Delivery'), ('S', 'Stripe'), ('P', 'Paypal')], max_length=2),
        ),
    ]
