# Generated by Django 3.0.7 on 2020-06-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0054_auto_20200630_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(max_length=50)),
            ],
        ),
    ]
