# Generated by Django 3.1.1 on 2020-11-15 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0056_auto_20201115_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, verbose_name='creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='modification date and time')),
                ('short_name', models.IntegerField(choices=[(10, 'New'), (30, 'Processing'), (40, 'Sent'), (50, 'Cancelled'), (60, 'in_transit'), (70, 'Delivered')], default=10)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('M', 'M-Pesa'), ('S', 'Stripe'), ('D', 'Debit Card'), ('C', 'Cash On Delivery'), ('P', 'Paypal')], max_length=2),
        ),
        migrations.AddField(
            model_name='order',
            name='status_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='me2ushop.statuscode'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='me2ushop.statuscode'),
        ),
    ]
