# Generated by Django 3.1.1 on 2020-11-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0057_auto_20201115_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='customer',
            new_name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('D', 'Debit Card'), ('P', 'Paypal'), ('C', 'Cash On Delivery'), ('S', 'Stripe'), ('M', 'M-Pesa')], max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='orderitem', to='me2ushop.OrderItem'),
        ),
        migrations.AlterField(
            model_name='statuscode',
            name='short_name',
            field=models.IntegerField(choices=[(10, 'New'), (20, 'Paid'), (30, 'Processing'), (40, 'Sent'), (50, 'Cancelled'), (60, 'in_transit'), (70, 'Delivered')], default=10),
        ),
    ]
