# Generated by Django 3.1.1 on 2021-03-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0058_auto_20210315_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('M', 'M-Pesa'), ('S', 'Stripe'), ('P', 'Paypal'), ('C', 'Cash On Delivery'), ('D', 'Debit Card')], max_length=2),
        ),
    ]
