# Generated by Django 3.1.1 on 2020-11-16 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0058_auto_20201116_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('S', 'Stripe'), ('P', 'Paypal'), ('C', 'Cash On Delivery'), ('D', 'Debit Card'), ('M', 'M-Pesa')], max_length=2),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status_code',
            field=models.ForeignKey(blank=True, default=10, null=True, on_delete=django.db.models.deletion.SET_NULL, to='me2ushop.statuscode'),
        ),
    ]
