# Generated by Django 3.1.1 on 2020-11-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0059_auto_20201116_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('D', 'Debit Card'), ('C', 'Cash On Delivery'), ('M', 'M-Pesa'), ('P', 'Paypal'), ('S', 'Stripe')], max_length=2),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
