# Generated by Django 3.0.7 on 2020-07-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0059_auto_20200630_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='made_in_africa',
            field=models.BooleanField(default=False),
        ),
    ]
