# Generated by Django 3.1.1 on 2021-03-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0059_auto_20210319_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('P', 'Paypal'), ('M', 'M-Pesa'), ('D', 'Debit Card'), ('C', 'Cash On Delivery'), ('S', 'Stripe')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('R', 'Refurbished'), ('N', 'New'), ('U', 'Used')], help_text='Choose the current condition for the product', max_length=2),
        ),
    ]
