# Generated by Django 3.1.1 on 2020-11-16 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0060_auto_20201116_2301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='order',
            new_name='customer_order',
        ),
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('M', 'M-Pesa'), ('D', 'Debit Card'), ('C', 'Cash On Delivery'), ('P', 'Paypal'), ('S', 'Stripe')], max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='me2ushop.OrderItem'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='me2ushop.statuscode'),
        ),
    ]
