# Generated by Django 3.1.1 on 2021-03-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0060_auto_20210320_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('D', 'Debit Card'), ('M', 'M-Pesa'), ('P', 'Paypal'), ('S', 'Stripe'), ('C', 'Cash On Delivery')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('R', 'Refurbished'), ('U', 'Used'), ('N', 'New')], help_text='Choose the current condition for the product', max_length=2),
        ),
    ]
