# Generated by Django 3.0.7 on 2020-07-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_category_image'),
        ('me2ushop', '0060_product_made_in_africa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], help_text='tags the product with NEW, primary blue, danger red, secondary', max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_categories',
            field=models.ManyToManyField(help_text='input the category above and any other where the product falls under.', to='categories.Category'),
        ),
    ]
