# Generated by Django 3.0.7 on 2020-07-08 00:49

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0061_auto_20200707_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=0, size=[340, 300], upload_to='images/products/main'),
        ),
    ]
