# Generated by Django 3.1.1 on 2021-03-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0061_auto_20210320_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('C', 'Cash On Delivery'), ('M', 'M-Pesa'), ('S', 'Stripe'), ('D', 'Debit Card'), ('P', 'Paypal')], max_length=2),
        ),
    ]
