# Generated by Django 3.0.7 on 2020-07-08 02:09

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0063_auto_20200708_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_std',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='images/products/main'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_std_thumbnail',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='images/products/thumbnail'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/thumbnail'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='images/products/main'),
        ),
    ]
