# Generated by Django 3.1.1 on 2020-11-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0063_auto_20201125_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('C', 'Cash On Delivery'), ('S', 'Stripe'), ('D', 'Debit Card'), ('M', 'M-Pesa'), ('P', 'Paypal')], max_length=2),
        ),
    ]
