# Generated by Django 3.0.7 on 2020-07-08 02:11

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0064_auto_20200708_0409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_std',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='images/products/main'),
        ),
    ]
