# Generated by Django 3.1.1 on 2020-11-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0064_auto_20201125_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('C', 'Cash On Delivery'), ('D', 'Debit Card'), ('M', 'M-Pesa'), ('P', 'Paypal'), ('S', 'Stripe')], max_length=2),
        ),
    ]
