# Generated by Django 3.1.1 on 2021-04-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0065_auto_20210411_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('M', 'M-Pesa'), ('C', 'Cash On Delivery'), ('P', 'Paypal'), ('D', 'Debit Card'), ('S', 'Stripe')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('U', 'Used'), ('R', 'Refurbished'), ('N', 'New')], help_text='Choose the current condition for the product', max_length=2),
        ),
    ]
