# Generated by Django 3.0.7 on 2020-07-08 02:12

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0065_auto_20200708_0411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_std_thumbnail',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='images/products/thumbnail'),
        ),
    ]
