# Generated by Django 3.0.7 on 2020-07-09 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0066_auto_20200708_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.CharField(blank=True, choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], help_text='tags the product with NEW, primary blue, danger red, secondary', max_length=1, null=True),
        ),
    ]
