# Generated by Django 3.0.7 on 2020-07-10 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0068_auto_20200710_0721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_bestseller',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_featured',
        ),
    ]
