# Generated by Django 3.0.7 on 2020-07-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0069_auto_20200710_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_choice',
            field=models.CharField(choices=[('Fe', 'Featured'), ('Be', 'Bestseller')], max_length=2),
        ),
    ]
