# Generated by Django 3.1.1 on 2021-04-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0070_auto_20210412_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertagtracker',
            name='tagname',
        ),
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('D', 'Debit Card'), ('M', 'M-Pesa'), ('P', 'Paypal'), ('S', 'Stripe'), ('C', 'Cash On Delivery')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('N', 'New'), ('R', 'Refurbished'), ('U', 'Used')], help_text='Choose the current condition for the product', max_length=2),
        ),
    ]
