# Generated by Django 3.0.7 on 2020-07-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0071_productreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='ordered_by_user',
        ),
        migrations.AlterField(
            model_name='productreview',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
