# Generated by Django 3.0.7 on 2020-07-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_category_image'),
        ('me2ushop', '0072_auto_20200711_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_bestseller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_choice',
            field=models.CharField(choices=[('At', 'Arts, Crafts'), ('Bk', 'Books'), ('Bb', 'Baby Care'), ('Be', 'Beautiful 2'), ('Ca', 'Camera & Photo'), ('S', 'Shirt'), ('Sw', 'Sport wear'), ('Ow', 'Outwear'), ('Am', 'Automotive & Motorcycle'), ('Ca', 'Cell Phones & Accessories'), ('El', 'Electronics'), ('Fa', 'Fashion'), ('Fu', 'Furniture')], help_text='Choose the main category for the product', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.CharField(blank=True, choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], help_text='tags the product primary blue, danger red, secondary purple', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_categories',
            field=models.ManyToManyField(help_text='input the category above and any other where the product can be found in.', to='categories.Category'),
        ),
    ]
