# Generated by Django 3.1.1 on 2021-04-12 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('me2ushop', '0073_auto_20210412_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('M', 'M-Pesa'), ('D', 'Debit Card'), ('P', 'Paypal'), ('C', 'Cash On Delivery'), ('S', 'Stripe')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('N', 'New'), ('U', 'Used'), ('R', 'Refurbished')], help_text='Choose the current condition for the product', max_length=2),
        ),
        migrations.AlterField(
            model_name='usertagtracker',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
