# Generated by Django 3.1.1 on 2021-04-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0074_auto_20210412_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('S', 'Stripe'), ('P', 'Paypal'), ('C', 'Cash On Delivery'), ('D', 'Debit Card'), ('M', 'M-Pesa')], max_length=2),
        ),
        migrations.DeleteModel(
            name='UserTagTracker',
        ),
    ]
