# Generated by Django 3.0.7 on 2020-07-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0075_auto_20200714_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cart_id',
            field=models.CharField(default='0000', max_length=70),
            preserve_default=False,
        ),
    ]
