# Generated by Django 3.0.7 on 2020-07-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0076_orderitem_cart_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_id',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
