# Generated by Django 3.0.7 on 2020-07-14 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0077_order_cart_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-order_date']},
        ),
    ]
