# Generated by Django 3.0.7 on 2020-07-15 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0078_auto_20200714_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart_id',
        ),
    ]
