# Generated by Django 3.1.1 on 2021-05-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0078_auto_20210423_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created'], 'verbose_name_plural': 'Products'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='product',
            name='created',
            field=models.DateTimeField(editable=False, null=True, verbose_name='creation date and time'),
        ),
        migrations.AddField(
            model_name='product',
            name='modified',
            field=models.DateTimeField(editable=False, null=True, verbose_name='modification date and time'),
        ),
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('P', 'Paypal'), ('M', 'M-Pesa'), ('S', 'Stripe'), ('D', 'Debit Card'), ('C', 'Cash On Delivery')], max_length=2),
        ),
        migrations.AlterField(
            model_name='brand',
            name='created',
            field=models.DateTimeField(editable=False, null=True, verbose_name='creation date and time'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(editable=False, null=True, verbose_name='creation date and time'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='created',
            field=models.DateTimeField(editable=False, null=True, verbose_name='creation date and time'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='created',
            field=models.DateTimeField(editable=False, null=True, verbose_name='creation date and time'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='created',
            field=models.DateTimeField(editable=False, null=True, verbose_name='creation date and time'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='created',
            field=models.DateTimeField(editable=False, null=True, verbose_name='creation date and time'),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='created',
            field=models.DateTimeField(editable=False, null=True, verbose_name='creation date and time'),
        ),
        migrations.AlterField(
            model_name='statuscode',
            name='created',
            field=models.DateTimeField(editable=False, null=True, verbose_name='creation date and time'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='created',
            field=models.DateTimeField(editable=False, null=True, verbose_name='creation date and time'),
        ),
    ]
