# Generated by Django 3.0.7 on 2020-07-15 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0079_remove_order_cart_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
