# Generated by Django 3.0.7 on 2020-07-15 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0080_order_tracking_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tracking_id',
        ),
        migrations.AddField(
            model_name='order',
            name='cart_id',
            field=models.CharField(default='1', max_length=70),
            preserve_default=False,
        ),
    ]
