# Generated by Django 3.1.1 on 2021-05-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0080_auto_20210520_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='valid_payment_method',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('M', 'M-Pesa'), ('S', 'Stripe'), ('P', 'Paypal')], max_length=2),
        ),
    ]
