# Generated by Django 3.1.1 on 2021-05-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0082_auto_20210520_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestrefund',
            name='email',
        ),
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('M', 'M-Pesa'), ('P', 'Paypal'), ('S', 'Stripe')], max_length=2),
        ),
    ]
