# Generated by Django 3.1.1 on 2021-05-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0083_auto_20210520_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestrefund',
            name='denied',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('S', 'Stripe'), ('P', 'Paypal'), ('M', 'M-Pesa')], max_length=2),
        ),
    ]
