# Generated by Django 3.1.1 on 2021-05-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0084_auto_20210520_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestrefund',
            name='denied',
        ),
        migrations.AlterField(
            model_name='order',
            name='refund_granted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='refund_requested',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestrefund',
            name='accepted',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
