# Generated by Django 3.0.7 on 2020-07-15 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0084_auto_20200715_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart_id',
            field=models.ForeignKey(max_length=70, on_delete=django.db.models.deletion.CASCADE, related_name='order_track_id', to='me2ushop.OrderItem'),
        ),
    ]
