# Generated by Django 3.1.1 on 2021-05-26 14:58

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import me2ushop.models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20210526_1658'),
        ('me2ushop', '0086_auto_20210522_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='application_status',
            field=models.IntegerField(blank=True, choices=[(10, 'Under Review'), (20, 'Active'), (30, 'Verified'), (40, 'Denied'), (50, 'Blocked')], default=10, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='business_email',
            field=models.EmailField(blank=True, help_text='Business Phone Number . i.e +250785....', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='business_phone',
            field=models.CharField(blank=True, help_text='Business Phone Number . i.e +250785....', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='business_registration_cert',
            field=stdimage.models.StdImageField(blank=True, help_text='Upload your business registration files to get a verified badge', null=True, upload_to='images/sellers/businessIDs'),
        ),
        migrations.AddField(
            model_name='brand',
            name='shipping_status',
            field=models.CharField(blank=True, choices=[('Cd', 'Can Ship Abroad and Deliver Locally'), ('Cl', 'Can Deliver Locally'), ('CO', 'Not Able to Deliver')], help_text='Is Your company able to ship or deliver your products once they buyers order online?', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('S', 'Stripe'), ('M', 'M-Pesa'), ('P', 'Paypal')], max_length=2),
        ),
        migrations.AlterField(
            model_name='brand',
            name='business_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='brand',
            name='country',
            field=django_countries.fields.CountryField(countries=me2ushop.models.AfrikanCountries, max_length=2),
        ),
        migrations.AlterField(
            model_name='brand',
            name='facebook',
            field=models.CharField(blank=True, help_text='Do you have a facebook page. Copy paste your page link here e.g..https://www.facebook.com/Me2UAfrika', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='instagram',
            field=models.CharField(blank=True, help_text='Do you have a instagram page. Copy paste your page link here eg..https://www.instagram.com/me2u_afrika/', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='subscription_type',
            field=models.CharField(choices=[('Fr', 'Free'), ('Bs', 'Basic'), ('Pr', 'Premium')], help_text="Select a monthly recurring subscription fees. It's free for all Sellers for the first 3 Months!", max_length=2),
        ),
        migrations.AlterField(
            model_name='brand',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='twitter',
            field=models.CharField(blank=True, help_text='Do you have a Telegram Channel. Copy paste your page link here. e.g..https://t.me/me2uafrika', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AlterField(
            model_name='product',
            name='additional_information',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Add product description', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='attribute',
            field=models.CharField(help_text='Add a product feature such as Weight', max_length=50),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='description',
            field=models.TextField(blank=True, help_text='Add some information to describe the attribute above.'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='value',
            field=models.CharField(help_text='Add the value of the attribute above i.e 1kg', max_length=50),
        ),
    ]
