# Generated by Django 3.1.1 on 2021-05-24 21:53

from django.db import migrations, models
import django_countries.fields
import me2ushop.models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0086_auto_20210522_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('S', 'Stripe'), ('M', 'M-Pesa'), ('P', 'Paypal')], max_length=2),
        ),
        migrations.AlterField(
            model_name='brand',
            name='country',
            field=django_countries.fields.CountryField(countries=me2ushop.models.AfrikanCountries, max_length=2),
        ),
    ]
