# Generated by Django 3.1.1 on 2021-05-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0086_auto_20210522_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='business_email',
            field=models.EmailField(blank=True, help_text='Business Phone Number . i.e +250785....', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='business_phone',
            field=models.CharField(blank=True, help_text='Business Phone Number . i.e +250785....', max_length=20, null=True),
        ),
    ]
