# Generated by Django 3.0.7 on 2020-07-15 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_auto_20200709_2017'),
        ('me2ushop', '0086_auto_20200715_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart_id',
            field=models.ForeignKey(max_length=70, on_delete=django.db.models.deletion.CASCADE, to='stats.ProductView'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='cart_id',
            field=models.ForeignKey(max_length=70, on_delete=django.db.models.deletion.CASCADE, to='stats.ProductView'),
        ),
    ]
