# Generated by Django 3.1.1 on 2021-05-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0087_auto_20210527_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='application_status',
            field=models.IntegerField(blank=True, choices=[(10, 'Under Review'), (20, 'Active'), (30, 'Verified'), (40, 'Denied'), (50, 'Blocked')], default=10, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='shipping_status',
            field=models.CharField(blank=True, choices=[('Cd', 'Can Ship Abroad and Deliver Locally'), ('Cl', 'Can Deliver Locally'), ('CO', 'Not Able to Deliver')], help_text='Is Your company able to ship or deliver your products once they buyers order online?', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='facebook',
            field=models.CharField(blank=True, help_text='Do you have a facebook page. Copy paste your page link here e.g..https://www.facebook.com/Me2UAfrika', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='instagram',
            field=models.CharField(blank=True, help_text='Do you have a instagram page. Copy paste your page link here eg..https://www.instagram.com/me2u_afrika/', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='twitter',
            field=models.CharField(blank=True, help_text='Do you have a Telegram Channel. Copy paste your page link here. e.g..https://t.me/me2uafrika', max_length=255, null=True),
        ),
    ]
