# Generated by Django 3.1.1 on 2021-05-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0087_auto_20210524_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('S', 'Stripe'), ('P', 'Paypal'), ('M', 'M-Pesa')], max_length=2),
        ),
        migrations.AlterField(
            model_name='brand',
            name='business_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='brand',
            name='subscription_type',
            field=models.CharField(choices=[('Fr', 'Free'), ('Bs', 'Basic'), ('Pr', 'Premium')], help_text="Select a monthly recurring subscription fees. It's free for all Sellers for the first 3 Months!", max_length=2),
        ),
        migrations.AlterField(
            model_name='brand',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
