# Generated by Django 3.0.7 on 2020-07-17 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0089_auto_20200717_0213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderanonymous',
            options={'ordering': ['-order_date'], 'verbose_name_plural': 'OrderAnonymous'},
        ),
    ]
