# Generated by Django 3.1.1 on 2021-05-25 02:29

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0090_auto_20210525_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='application_status',
            field=models.IntegerField(blank=True, choices=[(10, 'Under Review'), (20, 'Active'), (30, 'Verified'), (40, 'Denied'), (50, 'Blocked')], default=10, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='business_registration_cert',
            field=stdimage.models.StdImageField(blank=True, help_text='Upload your business registration files to get a verified badge', null=True, upload_to='images/sellers/businessIDs'),
        ),
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('M', 'M-Pesa'), ('S', 'Stripe'), ('P', 'Paypal')], max_length=2),
        ),
    ]
