# Generated by Django 3.1.1 on 2021-06-02 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0090_auto_20210601_1555'),
    ]

    operations = [
    ]
