# Generated by Django 3.0.7 on 2020-07-17 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stats', '0006_auto_20200717_0211'),
        ('me2ushop', '0090_auto_20200717_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='cart_id',
            field=models.ForeignKey(blank=True, max_length=70, null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.ProductView'),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
