# Generated by Django 3.0.7 on 2020-07-19 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0091_auto_20200717_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_thumbnail',
        ),
    ]
