# Generated by Django 3.1.1 on 2021-05-25 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('me2ushop', '0091_auto_20210525_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='business_email',
            field=models.EmailField(blank=True, help_text='Business Phone Number . i.e +250785....', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='business_phone',
            field=models.CharField(blank=True, help_text='Business Phone Number . i.e +250785....', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('P', 'Paypal'), ('M', 'M-Pesa'), ('S', 'Stripe')], max_length=2),
        ),
        migrations.AlterField(
            model_name='brand',
            name='facebook',
            field=models.CharField(blank=True, help_text='Do you have a facebook page. Copy paste your page link here e.g..https://www.facebook.com/Me2UAfrika', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='instagram',
            field=models.CharField(blank=True, help_text='Do you have a instagram page. Copy paste your page link here eg..https://www.instagram.com/me2u_afrika/', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='shipping_status',
            field=models.CharField(blank=True, choices=[('Cd', 'Can Ship Abroad and Deliver Locally'), ('Cl', 'Can Deliver Locally'), ('CO', 'Not Able to Deliver')], help_text='Is Your company able to ship or deliver your products once they buyers order online?', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='twitter',
            field=models.CharField(blank=True, help_text='Do you have a Telegram Channel. Copy paste your page link here. e.g..https://t.me/me2uafrika', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
