# Generated by Django 3.1.1 on 2021-05-25 16:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0093_auto_20210525_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('S', 'Stripe'), ('M', 'M-Pesa'), ('P', 'Paypal')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='additional_information',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Add product description', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='attribute',
            field=models.CharField(help_text='Add a product feature such as Weight', max_length=50),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='description',
            field=models.TextField(blank=True, help_text='Add some information to describe the attribute above.'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='value',
            field=models.CharField(help_text='Add the value of the attribute above i.e 1kg', max_length=50),
        ),
    ]
