# Generated by Django 3.0.7 on 2020-07-21 04:49

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0095_auto_20200720_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
