# Generated by Django 3.1.1 on 2021-06-17 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0098_auto_20210616_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='user',
        ),
    ]
