# Generated by Django 3.1.1 on 2021-06-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0104_auto_20210618_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='subscription_status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('M', 'M-Pesa'), ('S', 'Stripe'), ('P', 'Paypal')], max_length=2),
        ),
        migrations.AlterField(
            model_name='brand',
            name='subscription_type',
            field=models.CharField(choices=[('Fr', 'Free'), ('St', 'Standard'), ('Bs', 'Basic'), ('Pr', 'Premium')], help_text='Select a monthly recurring subscription fees', max_length=2),
        ),
    ]
