# Generated by Django 3.1.1 on 2021-06-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0108_auto_20210629_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='subscription_status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
