# Generated by Django 3.1.1 on 2021-06-29 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangorave', '0001_initial'),
        ('me2ushop', '0109_auto_20210629_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djangorave.drpaymenttypemodel'),
        ),
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('P', 'Paypal'), ('S', 'Stripe'), ('M', 'M-Pesa')], max_length=2),
        ),
    ]
