# Generated by Django 3.1.1 on 2021-06-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0110_auto_20210629_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='subscription_type',
        ),
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('P', 'Paypal'), ('M', 'M-Pesa'), ('S', 'Stripe')], max_length=2),
        ),
    ]
