# Generated by Django 3.1.1 on 2021-07-01 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0114_auto_20210701_0331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='subscription_status',
        ),
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('M', 'M-Pesa'), ('S', 'Stripe'), ('P', 'Paypal')], max_length=2),
        ),
    ]
