# Generated by Django 3.1.1 on 2021-07-20 22:42

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0121_auto_20210720_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='additional_information',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Provide additional information about your product. Buyers mostly buy from well detailed products and specifications', null=True),
        ),
    ]
