# Generated by Django 3.1.1 on 2021-07-21 15:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0123_auto_20210721_0146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='name',
            new_name='variation_name',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='attachment',
        ),
        migrations.AddField(
            model_name='productvariation',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Please note that the default currency is USD. Converty your product price to US Dollar before listing', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Please note that the default currency is USD. Converty your product price to US dollar before listing', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='variation_images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='me2ushop.productimage'),
        ),
        migrations.AlterUniqueTogether(
            name='variation',
            unique_together={('product', 'variation_name')},
        ),
    ]
