# Generated by Django 3.1.1 on 2021-07-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0124_auto_20210721_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='variation_images',
        ),
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('M', 'M-Pesa'), ('S', 'Stripe'), ('P', 'Paypal')], max_length=2),
        ),
    ]
