# Generated by Django 3.1.1 on 2021-07-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0125_auto_20210721_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='variation_images',
            field=models.ManyToManyField(to='me2ushop.ProductImage'),
        ),
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('P', 'Paypal'), ('M', 'M-Pesa'), ('S', 'Stripe')], max_length=2),
        ),
    ]
