# Generated by Django 3.1.1 on 2021-07-21 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0127_auto_20210721_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Please note that the default currency is USD. Converty your product price to US Dollar before listing', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Please note that the default currency is USD. Converty your product price to US dollar before listing', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='variation_images',
            field=models.ManyToManyField(to='me2ushop.ProductImage'),
        ),
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('P', 'Paypal'), ('S', 'Stripe'), ('M', 'M-Pesa')], max_length=2),
        ),
        migrations.DeleteModel(
            name='ProductVariation',
        ),
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
