# Generated by Django 3.1.1 on 2021-07-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0129_auto_20210721_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='value',
        ),
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('S', 'Stripe'), ('P', 'Paypal'), ('M', 'M-Pesa')], max_length=2),
        ),
    ]
