# Generated by Django 3.1.1 on 2021-07-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0130_auto_20210721_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='description',
        ),
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('P', 'Paypal'), ('M', 'M-Pesa'), ('S', 'Stripe')], max_length=2),
        ),
    ]
