# Generated by Django 3.1.1 on 2021-07-27 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0131_auto_20210721_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='title',
        ),
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('S', 'Stripe'), ('P', 'Paypal'), ('M', 'M-Pesa')], max_length=2),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='color',
            field=models.ForeignKey(blank=True, help_text='Add if your product comes in different colors', null=True, on_delete=django.db.models.deletion.CASCADE, to='me2ushop.color'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='If the above variables affect your original price, you can say how much this variant costs.Please note that the default currency is USD. Converty your product price to US dollar before listing', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='size',
            field=models.ForeignKey(blank=True, help_text='Add if your product comes in different sizes', null=True, on_delete=django.db.models.deletion.CASCADE, to='me2ushop.size'),
        ),
    ]
