# Generated by Django 3.1.1 on 2021-07-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0132_auto_20210727_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='size',
        ),
        migrations.AddField(
            model_name='productdetail',
            name='other_variant',
            field=models.CharField(blank=True, help_text='if you product has other variant like shape, Size or style, write it here instead', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='other_variant_value',
            field=models.CharField(blank=True, help_text="if you added other variant, please provide it's value, i.e if you added size value can be 16GB", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('M', 'M-Pesa'), ('P', 'Paypal'), ('S', 'Stripe')], max_length=2),
        ),
    ]
