# Generated by Django 3.1.1 on 2021-08-08 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0137_auto_20210731_0104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdetail',
            old_name='other_variant',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='other_variant_value',
        ),
        migrations.AddField(
            model_name='productdetail',
            name='size',
            field=models.ForeignKey(blank=True, help_text='Add if your product comes in different colors', null=True, on_delete=django.db.models.deletion.CASCADE, to='me2ushop.size'),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='stock',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('M', 'M-Pesa'), ('S', 'Stripe'), ('P', 'Paypal')], max_length=2),
        ),
    ]
