# Generated by Django 3.1.1 on 2021-09-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0140_auto_20210914_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='title',
            field=models.CharField(blank=True, help_text='Image title', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('S', 'Stripe'), ('M', 'M-Pesa'), ('P', 'Paypal')], max_length=2),
        ),
        migrations.AlterField(
            model_name='productvariations',
            name='title',
            field=models.CharField(blank=True, help_text='Title for this product variant', max_length=100, null=True),
        ),
    ]
