# Generated by Django 3.1.1 on 2021-09-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0141_auto_20210914_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_amount',
            field=models.IntegerField(blank=True, help_text='What is the maximum order units required for this item?', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='min_amount',
            field=models.IntegerField(blank=True, default=1, help_text='What is the minimum order units required for this item?'),
        ),
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('P', 'Paypal'), ('S', 'Stripe'), ('M', 'M-Pesa')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='What is the price of one piece of this item?Please note that the default currency is USD. Converty your product price to US dollar before listing.', max_digits=9),
        ),
    ]
