# Generated by Django 3.1.1 on 2021-10-05 08:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0142_auto_20210922_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariations',
            name='in_stock',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddField(
            model_name='productvariations',
            name='max_amount',
            field=models.IntegerField(blank=True, help_text='What is the maximum order units required for this item?', null=True),
        ),
        migrations.AddField(
            model_name='productvariations',
            name='min_amount',
            field=models.IntegerField(blank=True, default=1, help_text='What is the minimum order units required for this item?'),
        ),
        migrations.AddField(
            model_name='productvariations',
            name='sku',
            field=models.CharField(default='', editable=False, max_length=120),
        ),
        migrations.AlterField(
            model_name='productvariations',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Note that the default currency is USD. Convert your product price to US Dollar before listing', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='productvariations',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='If the above variables affect your original price, update priceNote that the default currency is USD. Convert your product price to US dollar before listing', max_digits=9, null=True),
        ),
    ]
