# Generated by Django 3.1.1 on 2021-10-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0143_auto_20211005_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('P', 'Paypal'), ('M', 'M-Pesa'), ('S', 'Stripe')], max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='productvariations',
            unique_together={('product', 'size', 'color')},
        ),
    ]
