# Generated by Django 3.1.1 on 2021-10-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0146_auto_20211007_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariations',
            name='slug',
            field=models.SlugField(blank=True, default='', editable=False, max_length=300, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('P', 'Paypal'), ('S', 'Stripe'), ('M', 'M-Pesa')], max_length=2),
        ),
    ]
