# Generated by Django 3.1.1 on 2021-10-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0148_auto_20211015_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='shipping_status',
        ),
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('M', 'M-Pesa'), ('S', 'Stripe'), ('P', 'Paypal')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='shipping_status',
            field=models.CharField(blank=True, choices=[('Cd', 'Can Ship Abroad and Deliver Locally'), ('Cl', 'Can Deliver Locally'), ('Co', 'Not Able to Deliver')], default='Cd', help_text='Is Your company able to ship or deliver this product once they buyers order online?', max_length=2, null=True),
        ),
    ]
