# Generated by Django 3.1.1 on 2021-10-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0150_auto_20211015_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shipping_status',
            field=models.CharField(blank=True, choices=[('Cd', 'Can Ship Abroad and Deliver Locally'), ('Cl', 'Can Deliver Locally(Within your country)'), ('Co', 'Not Able to Deliver')], default='Cd', help_text='Is Your company able to ship or deliver this product once they buyers order online?', max_length=2, null=True),
        ),
    ]
