# Generated by Django 3.1.1 on 2021-10-18 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0153_auto_20211018_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('M', 'M-Pesa'), ('S', 'Stripe'), ('P', 'Paypal')], max_length=2),
        ),
        migrations.CreateModel(
            name='ProductCustomizations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, null=True, verbose_name='creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='modification date and time')),
                ('name', models.CharField(max_length=255)),
                ('min_order', models.IntegerField(default=1)),
                ('max_order', models.IntegerField(blank=True, null=True)),
                ('customization_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='me2ushop.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
