# Generated by Django 3.1.1 on 2021-10-18 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me2ushop', '0156_auto_20211018_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='not_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('S', 'Stripe'), ('M', 'M-Pesa'), ('P', 'Paypal')], max_length=2),
        ),
    ]
