# Generated by Django 3.0.7 on 2020-07-27 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaDere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('Namba', models.CharField(max_length=13)),
                ('price_per_km', models.FloatField()),
                ('location', models.CharField(max_length=255)),
                ('availability', models.BooleanField()),
                ('image_url', models.CharField(blank=True, max_length=2083, null=True)),
                ('description', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('image_Ndai', models.ImageField(blank=True, null=True, upload_to='Ma_Ndai')),
                ('license_verified', models.BooleanField(default=False)),
                ('type_of_automobile', models.CharField(choices=[('BI', 'Baiskeli'), ('MK', 'MotorBike'), ('CR', 'Car'), ('LO', 'Lorry')], max_length=2)),
                ('customers', models.CharField(choices=[('A', 'Passengers'), ('M', 'Mizigo')], max_length=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
