# Generated by Django 3.1.1 on 2020-12-15 10:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=30)),
                ('message', models.TextField(help_text='Max length is 600 characters. Make your inquiry brief and to the point', max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='MaDere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('Namba', models.CharField(max_length=13)),
                ('price_per_km', models.FloatField()),
                ('location', models.CharField(max_length=255)),
                ('availability', models.BooleanField()),
                ('image_url', models.CharField(blank=True, max_length=2083, null=True)),
                ('description', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('image_Ndai', models.ImageField(blank=True, null=True, upload_to='Ma_Ndai')),
                ('license_verified', models.BooleanField(default=False)),
                ('type_of_automobile', models.CharField(choices=[('BI', 'Baiskeli'), ('MK', 'MotorBike'), ('CR', 'Car'), ('LO', 'Lorry')], max_length=2)),
                ('customers', models.CharField(choices=[('A', 'Passengers'), ('M', 'Mizigo')], max_length=1)),
            ],
        ),
    ]
