# Generated by Django 3.0.7 on 2020-08-16 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200814_0726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketline',
            name='basket',
        ),
        migrations.RemoveField(
            model_name='basketline',
            name='product',
        ),
        migrations.DeleteModel(
            name='Basket',
        ),
        migrations.DeleteModel(
            name='BasketLine',
        ),
    ]
