# Generated by Django 3.1.1 on 2020-11-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.TextField(help_text='Max length is 600 characters. Make your inquiry brief and to the point', max_length=600),
        ),
    ]
