# Generated by Django 3.1.1 on 2020-10-08 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_bestselling',
            field=models.BooleanField(default=False),
        ),
    ]
