# Generated by Django 3.0.7 on 2020-07-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='made_in_africa',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
