# Generated by Django 3.1.1 on 2021-02-03 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_department_icon_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='sub_category_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.category'),
        ),
    ]
