# Generated by Django 3.1.1 on 2020-10-08 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_department_is_bestselling'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='icon_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
