# Generated by Django 3.0.7 on 2020-07-05 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_made_in_africa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='made_in_africa',
        ),
    ]
