# Generated by Django 3.0.7 on 2020-07-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_remove_category_made_in_africa'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default=False, null=True, upload_to=''),
        ),
    ]
