# Generated by Django 3.0.7 on 2020-07-22 00:05

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='images/category'),
        ),
    ]
