# Generated by Django 3.1.1 on 2021-05-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_auto_20210520_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='slug',
            field=models.SlugField(editable=False, help_text='Unique value for product page URL, created from name.', unique=True),
        ),
    ]
