# Generated by Django 3.1.1 on 2021-05-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_auto_20210520_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
