# Generated by Django 3.0.7 on 2020-06-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Me2UAfricaMain', '0003_auto_20200617_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='madere',
            name='AINA_YA_NDAI',
            field=models.CharField(choices=[('BI', 'Baiskeli'), ('MK', 'MotorBike'), ('CR', 'Car'), ('LO', 'Lorry')], max_length=2),
        ),
        migrations.AlterField(
            model_name='madere',
            name='image_Ndai',
            field=models.ImageField(blank=True, null=True, upload_to='Ma_Ndai'),
        ),
        migrations.AlterField(
            model_name='madere',
            name='image_url',
            field=models.CharField(blank=True, max_length=2083, null=True),
        ),
    ]
