# Generated by Django 3.0.7 on 2020-06-17 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Me2UAfricaMain', '0005_auto_20200617_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='madere',
            old_name='Namba_Zao',
            new_name='Namba',
        ),
    ]
