# Generated by Django 3.0.7 on 2020-06-17 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Me2UAfricaMain', '0006_auto_20200617_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='madere',
            old_name='WATEJA',
            new_name='customers',
        ),
        migrations.RenameField(
            model_name='madere',
            old_name='AINA_YA_NDAI',
            new_name='type_of_automobile',
        ),
    ]
