# Generated by Django 3.1.1 on 2020-12-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.CharField(max_length=50)),
                ('search_date', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('category_searched', models.CharField(blank=True, default='All categories', max_length=150, null=True)),
                ('tracking_id', models.CharField(default='', max_length=70)),
            ],
            options={
                'ordering': ['-search_date'],
            },
        ),
    ]
