# Generated by Django 3.0.7 on 2020-07-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_searchterm_tracking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchterm',
            name='tracking_id',
            field=models.CharField(default='', max_length=70),
        ),
    ]
