# Generated by Django 3.1.1 on 2020-10-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_searchterm_category_searched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchterm',
            name='category_searched',
            field=models.CharField(blank=True, default='All categories', max_length=150, null=True),
        ),
    ]
