# Generated by Django 3.0.7 on 2020-07-20 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20200709_2030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchterm',
            options={'ordering': ['-search_date']},
        ),
    ]
