# Generated by Django 3.0.7 on 2020-06-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaDriversWetu', '0004_auto_20200617_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='madere',
            name='Namba_Zao',
            field=models.CharField(max_length=13),
        ),
    ]
